name: test
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@7c12f8017d5436eb855f1ed4399f037a36fbd9e8 # v2.5.2
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install
    - name: Run scripts
      run: |
        yarn run lint
        yarn audit
        yarn test
